### ISSUE TITLE
Runtime error with cli_demo.py

### ISSUE THREAD

**Issue by loyo1990** [shubhtuls/factored3d#11]
Hi, I am getting this Runtime error: sizes do not match
when I am trying to run cli_demo.py
Here is the description:

----> 1 objects, layout = tester.predict_factored3d()

/vulcan/scratch/luyu/source/others/factored3d/../factored3d/demo/demo_utils.pyc in predict_factored3d(self)
    211         print(self.rois)
    212         codes_pred_all, labels_pred = self.oc3d_model.forward(
--> 213             (self.input_imgs_fine, self.input_imgs, self.rois))
    214         scores_pred = labels_pred.cpu().data.numpy()
    215         bboxes_pred = self.rois.data.cpu().numpy()[:, 1:]

/vulcan/scratch/luyu/source/others/factored3d/../factored3d/nnutils/oc_net.pyc in forward(self, imgs_rois)
    214         img_feat_fine = self.resnet_conv_fine.forward(imgs_inp_fine)
    215
--> 216         roi_img_feat = self.roi_pool.forward(img_feat_fine, rois_inp)
    217         roi_img_feat = roi_img_feat.view(roi_img_feat.size(0), -1)
    218

/vulcan/scratch/luyu/source/others/factored3d/../factored3d/nnutils/roi_pool_py.py in forward(self, features, rois)
     47                         data = features[batch_ind]
     48                         outputs[roi_ind, :, ph, pw] = torch.max(
---> 49                             torch.max(data[:, hstart:hend, wstart:wend], 1)[0], 1)[0].view(-1)
     50
     51         return outputs

/vulcan/scratch/luyu/anaconda3/envs/t2/lib/python2.7/site-packages/torch/autograd/variable.pyc in __setitem__(self, key, value)
     78         else:
     79             if isinstance(value, Variable):
---> 80                 return SetItem(key)(self, value)
     81             else:
     82                 return SetItem(key, value)(self)

/vulcan/scratch/luyu/anaconda3/envs/t2/lib/python2.7/site-packages/torch/autograd/_functions/tensor.pyc in forward(self, i, value)
     37         else:  # value is Tensor
     38             self.value_size = value.size()
---> 39         i._set_index(self.index, value)
     40         return i
     41
RuntimeError: sizes do not match at /opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/THC/THCTensorCopy.cu:31

**Comment by shubhtuls** [comment]
Hi,
You seem to be using pytorch 0.1.12. We tested the code using version 0.2. Perhaps you could use that version and see if the error still persists.

**Comment by loyo1990** [comment]
It worked.
Thanks!

**Comment by santhu937** [comment]
hi, I'm getting runtime error while running cli_demo.py, I ran on CPU by removing coda() calls and used pytorch 0.2.0 and python 2.7

Traceback (most recent call last):
File "cli_demo.py", line 55, in 
objects, layout = tester.predict_factored3d()
File "/Users/santhosh/Documents/factored3d/../factored3d/demo/demo_utils.py", line 210, in predict_factored3d
(self.input_imgs_fine, self.input_imgs, self.rois))
File "/Users/santhosh/Documents/factored3d/../factored3d/nnutils/oc_net.py", line 216, in forward
roi_img_feat = self.roi_pool.forward(img_feat_fine, rois_inp)
File "/Users/santhosh/Documents/factored3d/../factored3d/nnutils/roi_pool_py.py", line 49, in forward
torch.max(data[:, hstart:hend, wstart:wend], 1)[0], 1)[0].view(-1)
File "/Users/santhosh/Desktop/iisc/san/lib/python2.7/site-packages/torch/autograd/variable.py", line 85, in setitem
return SetItem.apply(self, key, value)
File "/Users/santhosh/Desktop/iisc/san/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 43, in forward
i._set_index(ctx.index, value)
RuntimeError: inconsistent tensor size, expected tensor [256] and src [512] to have the same number of elements, but got 256 and 512 elements respectively at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorCopy.c:86

@loyo1990 @shubhtuls @s-gupta @dfouhey  , thank you
