### ISSUE TITLE
Does it require python 2.7 or 3.X?

### ISSUE THREAD

**Issue by loyo1990** [shubhtuls/factored3d#12]
Hi, I built two different conda envs, one using python2.7, another 3.6.5.
With the same packages installed.

If I am using the python2.7 I am getting the same error as qasim's earlier.
"""
No such file or directory: '/vulcan/scratch/luyu/source/others/factored3d/demo/../cachedir/rendering/dwr_shape_ft/rendering/render_000.png'
"""
It seems like a python version problem based on your conversation.
However if I use the python3.6.5 environment, I get
"""
ImportError: dynamic module does not define module export function (PyInit_bbox_utils)
"""
which also seems like a version problem.

**Comment by shubhtuls** [comment]
Use python 2.7. Closing this issue as this error is already addressed in [this existing issue](https://github.com/shubhtuls/factored3d/issues/9).
