### ISSUE TITLE
Is it possible to run this code with custom input images?

### ISSUE THREAD

**Issue by alpErenSari** [shubhtuls/factored3d#14]
Hello, I want to test your code with some images. I have run the demo ;however, I couldn't find any way to calculate proposal.mat file for a custom image file. Is it possible ?

**Comment by shubhtuls** [comment]
Thanks for the interest in the code. Perhaps you could take a look at how the proposals are computed for the suncg images [here](https://github.com/shubhtuls/factored3d/blob/master/preprocess/suncg/precompute_edge_boxes.m) (there relevant lines are [these](https://github.com/shubhtuls/factored3d/blob/master/preprocess/suncg/precompute_edge_boxes.m#L65-L67)) and similarly obtain edgebox proposals for the new images of interest.

**Comment by alpErenSari** [comment]
thanks for the response
