### ISSUE TITLE
unable to load cachedir.tar.gz

### ISSUE THREAD

**Issue by berak** [shubhtuls/factored3d#15]
https://people.eecs.berkeley.edu/~shubhtuls/ redirects to https://shubhtuls.github.io , and ofc. there's nothing to be found ;(

**Comment by shubhtuls** [comment]
Hi,
Yes, unfortunately my Berkeley page became inactive a couple od days back, and I haven't found a permanent home for the data yet. [Here](https://www.dropbox.com/sh/dg82g87yvhkg9xk/AAD5Drgr0fzGhWPkYRVDf8Pza?dl=0) is a temporary link that might be useful in the meantime.

**Comment by berak** [comment]
super, thank you ! 
(that was the only missing part !)
