### ISSUE TITLE
Download Links to the Berkeley website are outdated

### ISSUE THREAD

**Issue by tonyromarock** [shubhtuls/factored3d#16]
Hi Shubham,

Most of the links referred in [suncg_data.md](https://github.com/shubhtuls/factored3d/blob/master/docs/suncg_data.md) are outdated. They are still linking to your Berkeley page, although it seems that you are relocating your content over to your GitHub page.

Can you please make the following files available again to allow further research on this project:
- suncg_split.pkl
- layout.tar.gz
- ModelCategoryMappingEdited.csv

Thanks a lot,
Peter

**Comment by shubhtuls** [comment]
Please see #15

**Comment by tonyromarock** [comment]
I see. Sorry, I should have checked the resolved issues more closely. 
Thank you for the fast response.
