### ISSUE TITLE
Is there anyone reproduce table 1 result?

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [shubhtuls/factored3d#17]
Is there anyone reproduce table 1 result? I test on parts of the test data, and got the following AP values, which is much lower than the one from paper.

metric | shape | rot | translation | scale
--| -- | -- | -- | --
 method |%(IoU > 0.25) | %(Err < 30) | %(Err < 1m) | %(err<0.5)
reproduction | 48.37 | 50.171 | 62.589 | 48.138
(paper) | 70.7 | 74.6 | 87.3 | 85.1

My settings are using the ground truth bounding boxes as test data proposals, and shape %(IoU > 0.25)  as AP(box_iou=0, shape_threshold=0.25, rotation_threshold=400, translation_threshold=1000, scale_threshold=100), rot %(Err<30) as AP(box_iou=0, shape_threshold=0, rotation_threshold=30, translation_threshold=1000, scale_threshold=100) similar for translation and scale. I'm using the [dwr.py](https://github.com/shubhtuls/factored3d/blob/master/benchmark/suncg/dwr.py ) script.

**Comment by shubhtuls** [comment]
Hi @KnightOfTheMoonlight ,
I don't think computing AP using GT boxes is the corresponding thing - what you're actually looking for is analogous to the recall at the 'end of the curve'. Even then, it might be different because of NMS etc.

Below is the code for the 'test' function to generate this table - it's from a slightly older version of this repo so might need to be edited a bit. Please let me know if you have more questions.

```python
    def test(self):
        opts = self.opts
        # codes are (shapes, scales, quats, trans)
        n_iter = len(self.dataloader)
        err_trans_tensors = []
        err_scale_tensors = []
        err_shape_tensors = []
        err_rot_tensors = []
        for i, batch in enumerate(self.dataloader):
            if i % 100 == 0:
                print('{}/{} evaluation iterations.'.format(i, n_iter))
            if opts.max_eval_iter > 0 and (i >= opts.max_eval_iter):
                break

            iter_start_time = time.time()
            self.set_input(batch)
            if not self.invalid_batch:
                num_instances = self.rois.size()[0]

                self.codes_pred = self.model.forward((self.input_imgs_fine, self.input_imgs, self.rois))
                codes_pred_eval = [t for t in self.codes_pred]
                codes_pred_eval[0] = self.decode_shape(codes_pred_eval[0])
                codes_pred_eval[2] = self.decode_rotation(codes_pred_eval[2])


                for b in range(num_instances):
                    err_trans = (codes_pred_eval[3][b] - self.codes_gt[3][b]).norm(dim=0)
                    err_trans_tensors.append(err_trans.data[0])

                    err_scale = (codes_pred_eval[1][b].log() - self.codes_gt[1][b].log()).abs().mean(dim=0)/np.log(2.0)
                    err_scale_tensors.append(err_scale.data[0])

                    err_shape = metrics.volume_iou(
                        codes_pred_eval[0][b,0].data, self.codes_gt[0][b,0].data, thresh=opts.voxel_eval_thresh)
                    err_shape_tensors.append(err_shape)

                    err_rot = metrics.quat_dist(codes_pred_eval[2][b].data.cpu(), self.codes_gt[2][b].data.cpu())
                    err_rot_tensors.append(err_rot)


        err_shape_tensors = np.array(err_shape_tensors)
        err_scale_tensors = np.array(err_scale_tensors)
        err_trans_tensors = np.array(err_trans_tensors)
        err_rot_tensors = np.array(err_rot_tensors)
        results_file = osp.join(FLAGS.results_eval_dir, 'results.mat')
        results = {}
        results['iou_shape'] = err_shape_tensors.reshape((-1, 1))
        results['err_scale'] = err_scale_tensors.reshape((-1, 1))
        results['err_rot'] = err_rot_tensors.reshape((-1, 1))
        results['err_trans'] = err_trans_tensors.reshape((-1, 1))

        print(
            np.median(err_shape_tensors), np.median(err_scale_tensors),
            np.median(err_trans_tensors), np.median(err_rot_tensors))

```

**Comment by KnightOfTheMoonlight** [comment]
@shubhtuls  Thanks for your response and help for evaluating mean Delta values. From my understanding, your code is for mean Delta value. Right? And I'm asking about the Average Precision values. Table 1 is about the meanDelta and AP performance of predictions on SUNCG with ground-truth boxes.  And I still don't understand what are u trying to say about "analogous to the recall at the 'end of the curve'" too. The PR curve figures (fig. 7) are calculated based on the test proposals, but these values in table 1 should be calculated based on ground truth bboxes, right?

**Comment by shubhtuls** [comment]
I am slightly confused by the question. Table 1 is NOT about 'AP performance of predictions on SUNCG with ground-truth boxes'. We just report the accuracy and median error for predictions with GT boxes.

As an example, if we had 5 instances in the dataset, and the translation error for those w.r.t. ground-truth was 0.1m, 0.2m, 1.2m, 0.5m and 0.6m, then Table 1 would report (for trasnlation) an 'Accuracy' of 80%, and median error of 0.5m. This is not Average Precision.

**Comment by KnightOfTheMoonlight** [comment]
I see. Cause in sec 4.3, qualitative results part, figure 3 is for "Predicted 3D representation using ground-truth boxes".  Quantitative results part, table 1 is for "Performance of predictions on SUNCG with ground-truth boxes".  So I think both of them are based on test using ground truth bboxes.

**Comment by KnightOfTheMoonlight** [comment]
And I still think this is the way you trying to illustrate 3d object shape and pose estimation results purely without 2d detection.

**Comment by shubhtuls** [comment]
@KnightOfTheMoonlight - both the above statements you make are correct. Fig 3 and Table 1 do report evaluation/visualization with GT boxes. It's just that the evaluation metric used with GT boxes is not average precision.

**Comment by KnightOfTheMoonlight** [comment]
Thanks! I'm clear now. The problem is dwr.py evaluate pred with every ground truth results.

**Comment by KnightOfTheMoonlight** [comment]
Sorry to ask after such a long time. But I'm wondering, which model did you use for this setting. is it `dwr_shape_ft`?

**Comment by shubhtuls** [comment]
yes, the 'Base + decoder finetuning' row in table 1 does correspond to  'dwr_shape_ft' model.
