### ISSUE TITLE
Bad file descriptor when num_workers > 0 

### ISSUE THREAD

**Issue by ashariati** [shubhtuls/factored3d#2]
Hello @shubhtuls ,

I have tracked the following error `OSError: [Errno 9] Bad file descriptor` to the point when the suncg dataloader is passed to `enumerate()` for training. It seems however it only shows up when the num_workers > 0, and suncg_dl_out_codes=True, and from there it seems like a mess to debug. Have you ever come across this? 

I am using python 3.6.4 with the latest version of pytorch, and have only processed data from the first 100 houses just to get things started for myself. Below is my code:

```
flags.DEFINE_integer('max_rois', 5, 'If we have more objects than this per image, we will subsample.')

FLAGS = flags.FLAGS

class LayoutTrainer(train_utils.Trainer):

    def define_model(self):
        return

    def init_dataset(self):
        opts = self.opts
        split_dir = osp.join(opts.suncg_dir, 'splits')
        self.split = suncg_parse.get_split(split_dir, house_names=os.listdir(osp.join(opts.suncg_dir, 'camera')))
        self.dataloader = suncg_data.suncg_data_loader(self.split['train'], opts)

    def define_criterion(self):
        self.criterion = None

    def train(self):

        for i, batch in enumerate(self.dataloader):
            print(i)
            continue

        print('this better?')

def main(_):
    FLAGS.suncg_dl_out_layout = True
    FLAGS.suncg_dl_out_depth = True
    FLAGS.suncg_dl_out_fine_img = True
    FLAGS.suncg_dl_out_codes = True
    FLAGS.suncg_dl_out_voxels = False
    FLAGS.suncg_dl_out_proposals = False

    torch.manual_seed(0)
    trainer = LayoutTrainer(FLAGS)
    trainer.init_dataset()
    trainer.train()

if __name__ == '__main__':
    app.run(main)
```

The only lines in your code I needed to change from your code is line 288 of suncg_parse.py (changing .has_key() to python3 convention of key in d.keys()) as well as lines 171 and 172 of suncg_parse.py to use the updated key names in the data (i.e. ids instead of node_ids, nPixels instead of n_pixels).

Thanks in advance

**Comment by shubhtuls** [comment]
Hi @ashariati ,
Thanks for the query. Yes, I also ran into this and spent some time debugging but to no avail. This is why the example scripts have 'num_workers = 0' (i.e no parallelization in data loading). I'd recommend using that setting for now.

**Comment by ashariati** [comment]
@shubhtuls thanks for the fast response, 

Sure thing, great, just glad to know its not just me.
