### ISSUE TITLE
Running Demo

### ISSUE THREAD

**Issue by qasimz** [shubhtuls/factored3d#6]
Hi,
I have installed all the required items that are described in installation.md. I just want to run the demo. What I have to do next?

**Comment by shubhtuls** [comment]
Hi,
You can try the [interactive notebook](https://github.com/shubhtuls/factored3d/blob/master/demo/demo.ipynb) which shows reconstructions using the learned models. If you prefer to not use iPython notebooks, you can run the demo using the [python script](https://github.com/shubhtuls/factored3d/blob/master/demo/cli_demo.py).
