### ISSUE TITLE
Error while compiling cython modules

### ISSUE THREAD

**Issue by asim645** [shubhtuls/factored3d#7]
when i use cmd

mv factored3d/utils/bbox_utils.so ./

i get error mv: cannot stat 'factored3d/utils/bbox_utils.so': No such file or directory

**Comment by shubhtuls** [comment]
Hi,
Did this compile for you? I think the steps below should work -
```
cd utils
python setup.py build_ext --inplace
```

**Comment by asim645** [comment]
i used this cmd as as .so file had different file name in folder
mv factored3d/utils/bbox_utils.cpython-35m-x86_64-linux-gnu.so ./

now am getting issues because of cpu

**Comment by shubhtuls** [comment]
Interesting, thanks for pointing out the the workaround for the differently named file. Closing this issue because the GPU requirement is already discussed in a different thread.
