### ISSUE TITLE
Error in running demo

### ISSUE THREAD

**Issue by asim645** [shubhtuls/factored3d#8]
while trying to run demo 
~/factored3d$ python3 cli_demo.py 
i get error
Traceback (most recent call last):
  File "cli_demo.py", line 12, in <module>
    from factored3d.demo import demo_utils
ImportError: No module named 'factored3d'

**Comment by shubhtuls** [comment]
Did you edit the ‘code_root’ path in the demo file as instructed in the comment at the start?

**Comment by asim645** [comment]
factored3d was cloned in home folder, so i edited it as
code_root = '/Home/factored3d/'

**Comment by asim645** [comment]
i have changed 'code_root'path. now getting error
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by asim645** [comment]
can demo run with CPU only

**Comment by shubhtuls** [comment]
Closing the issue since original problem was resolved. Please see [this issue](https://github.com/shubhtuls/factored3d/issues/5) for the followup.
